version: "3.9"
services:
  mysql:
      image: mysql/mysql-server:latest
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "carDealership"
        MYSQL_USER: "anurag"
        MYSQL_PASSWORD: "anur@12"
      restart: always
      ports:
        - 3307:3307
  car_dealership:
    image: car_dealership:latest
    restart: always
    ports:
      - 2000:2000
